### ISSUE TITLE
[BUG] Some links don’t embed due to failure in reading containing_thread property

### ISSUE THREAD

**Issue by SuperSajuuk** [milanmdev/fixthreads#67]
Hi there, i tried to post this link on Discord to embed the video as intended: https://www.fixthreads.net/@mrsloppybeanz/post/C4wQoY4oHY6

unfortunately it doesn’t embed due to this error: `{"error":true,"message":"Cannot read properties of undefined (reading 'containing_thread')"}`

hopefully this can be fixed! Great website btw :)

**Comment by milanmdev** [comment]
Fixed in 822ac03. The code will be live on fixthreads.net shortly.
